version: '3.7'
services:
  web:
    build: ./scripts/web
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./scripts/web/src/:/var/www/html
    ports:
      - 80:80
  mysql:
    build: ./scripts/mysql
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./volume/datadir:/var/lib/mysql
    ports:
      - 3306:3306
